main: MCSOS.java
	echo -------Compiling MCSOS.java to create executable MCSOS---------
	javac MCSOS.java

run:
	java MCSOS

clean:
	echo -------Removing executable program MCSOS----------
	/bin/rm MCSOS.class
	/bin/rm -rf output/PRINTER*
